name: common
description: 커먼 모바일

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  json_annotation: ^4.7.0
  flutter_svg: ^2.0.1

  cloud_firestore: ^4.3.1
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.10
  firebase_messaging: ^14.0.3
  flutter_local_notifications: ^13.0.0

  crypto: ^3.0.2

  http: ^0.13.5

  scrollable_positioned_list: ^0.3.5
  another_flushbar: ^1.12.29

  image_picker: ^0.8.6+1

  shared_preferences: ^2.0.17

  provider: ^6.0.5

  flutter_speed_dial: ^6.2.0

  flutter_localization: ^0.1.11
  intl: ^0.18.0

  url_launcher: ^6.1.10

  dotted_border: ^2.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.5.4
  build_runner: ^2.3.3

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/svg/
    - assets/icons/nav/
    - assets/images/
    - assets/category/
    - assets/mini_category/

  fonts:
    - family: AppleSDGothicNeo
      fonts:
        - asset: assets/fonts/AppleSDGothicNeoM.ttf
          weight: 400
        - asset: assets/fonts/AppleSDGothicNeoB.ttf
          weight: 700