name: common
description: 커먼 모바일

version: 1.0.2+4

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  json_annotation: ^4.8.1
  flutter_svg: ^2.0.7

  cloud_firestore: ^4.3.1
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.10
  firebase_messaging: ^14.0.3
  flutter_local_notifications: ^13.0.0

  crypto: ^3.0.2

  http: ^1.1.0

  scrollable_positioned_list: ^0.3.8
  another_flushbar: ^1.12.30

  image_picker: ^1.0.4

  shared_preferences: ^2.2.1

  provider: ^6.0.5

  flutter_speed_dial: ^7.0.0

  flutter_localization: ^0.1.14
  intl: ^0.18.0

  url_launcher: ^6.1.14

  dotted_border: ^2.0.0+3

  image_gallery_saver: ^2.0.3
  permission_handler: ^11.0.0

  cached_network_image: ^3.2.3

  package_info_plus: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.5.4
  build_runner: ^2.3.3

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/svg/
    - assets/icons/nav/
    - assets/images/
    - assets/category/
    - assets/mini_category/

  fonts:
    - family: AppleSDGothicNeo
      fonts:
        - asset: assets/fonts/AppleSDGothicNeoM.ttf
          weight: 400
        - asset: assets/fonts/AppleSDGothicNeoB.ttf
          weight: 700