name: common
description: 커먼 모바일

version: 1.0.4+7

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  json_annotation: ^4.8.1
  flutter_svg: ^2.0.9

  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.1+1

  crypto: ^3.0.3

  http: ^1.2.0

  scrollable_positioned_list: ^0.3.8
  another_flushbar: ^1.12.30

  image_picker: ^1.0.7

  shared_preferences: ^2.2.2

  provider: ^6.1.1

  flutter_speed_dial: ^7.0.0

  flutter_localization: ^0.2.0
  intl: ^0.18.1

  url_launcher: ^6.2.3

  dotted_border: ^2.1.0

  image_gallery_saver: ^2.0.3
  permission_handler: ^11.2.0

  cached_network_image: ^3.3.1

  package_info_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.8

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/svg/
    - assets/icons/nav/
    - assets/images/
    - assets/category/
    - assets/mini_category/

  fonts:
    - family: AppleSDGothicNeo
      fonts:
        - asset: assets/fonts/AppleSDGothicNeoM.ttf
          weight: 400
        - asset: assets/fonts/AppleSDGothicNeoB.ttf
          weight: 700